---
version: "3"
services:
  mmoaig:
    build:
      context: ./
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig
    network_mode: service:db
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    expose:
      - "5432"
    volumes:
      - "database:/var/lib/postgresql/data"

volumes:
  database: